# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Beach.create(name: 'Good Harbor Beach', town: 'Gloucester', state: 'MA', description: 'Located on Thatcher Road/Route 127A, Good Harbor is a beautiful beach with lovely white sand. At low tide, one can walk out to Salt Island, while at high tide, one can enjoy body surfing or boogie boards.', url:'https://www.gloucester-ma.gov/1215/Gloucester-Beaches---Detailed-Informatio' , image: 'https://flic.kr/p/8WoLFj')
Beach.create(name: 'Wingaersheek', town: 'Gloucester', state: 'MA', description: 'Situated in the western part of Gloucester at the end of Atlantic Street off Route 133 and Concord Street, this beautiful beach runs along the Annisquam River and Ipswich Bay. At low tide, the beach extends out for hundreds of yards and a long sandbar is exposed, making for a great place to walk.', url: 'https://www.gloucester-ma.gov/1215/Gloucester-Beaches---Detailed-Informatio', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Wingaersheek_sunset.JPG/802px-Wingaersheek_sunset.JPG?20120919010648' )
Beach.create(name: 'Stage Fort Park', town: 'Gloucester', state: 'MA', description: 'This historic park is the site of Gloucester’s first settlers in 1623 who set up fishing stages on this land upon arrival. Stage Fort Park is home to Half Moon and Cressy’s beaches, with access to a sand volleyball court, a beautiful new playground, a baseball field, a basketball court, and tennis courts. There are plenty of picnic tables and cStage Fort Parkooking areas (bring your own grill), a privately owned restaurant that is open to the public, an information center, and restrooms. During the summer season, there are outdoor concerts, fireworks, and storytelling events for children, festivals, farmers markets, and several other events.', url: 'https://www.gloucester-ma.gov/450/Parks-and-Recreational-Facilities', image: 'https://flic.kr/p/Lyrku8')